name: litenet
description: "LiteNet Mobile Application"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  # build_runner: ^2.10.4
  change_app_package_name: ^1.5.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.12.0
  flutter_hooks: ^0.21.3+1
  flutter_launcher_icons: ^0.14.4
  flutter_map: ^8.2.2
  flutter_svg: ^2.2.3
  geolocator: ^14.0.2
  go_router: ^17.1.0
  http: ^1.6.0
  latlong2: ^0.9.1
  permission_handler: ^12.0.1
  
  # Riverpod (Stable for Flutter 3.35)
  flutter_riverpod: ^3.0.3
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  
  # Generator (DOWNGRADED)
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "#EFECFF"
  background_color_ios: "#EFECFF"

  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#efecff"
    theme_color: "#efecff"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/Montserrat/
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
